
create table site_sale_status_new (
             id serial,
             STATUS_ID varchar(5) unique,
             SORT int,
             "type"	varchar(5),
             "notify" char(1),
             COLOR	varchar(100),
             description varchar(200),
     primary key (id)
  );
 
----------------------------------------------------
create table site_location_country_new(
             id serial,
             country_id int,
             "name" varchar(100),
             short_name varchar(100),
     primary key (id)          
);
---------------------------------------------------
create table site_location_city_new (
             id serial,
             city_id int,
             "name" varchar(100),
             region_id int,
             short_name varchar(100),
     primary key (id)
);
 ----------------------------------------------------
 create table site_user_new (
             ID int,            
             DATE_REGISTER timestamp,
             TIMESTAMP_X timestamp,
             ACTIVE	char(1),
             ADMIN_NOTES text,
             AUTO_TIME_ZONE char(1),
             "blocked" char(1),
             BX_USER_ID	varchar(300),
             CHECKWORD	varchar(300),
             CHECKWORD_TIME	timestamp,
             CONFIRM_CODE varchar(10),
             EMAIL varchar(100),
             EXTERNAL_AUTH_ID varchar(200),
             LANGUAGE_ID char(2),
             LAST_ACTIVITY_DATE	timestamp,
             LAST_LOGIN	timestamp,
             "name"	varchar(150),
             LAST_NAME varchar(150),
             SECOND_NAME varchar(100),
             LID char(2),
             LOGIN varchar(150),
             LOGIN_ATTEMPTS	int,
             "password"	varchar(300),
             PASSWORD_EXPIRED char(1),
             PERSONAL_BIRTHDATE	varchar(50),
             PERSONAL_BIRTHDAY	date,
             PERSONAL_CITY	varchar(100),
             PERSONAL_COUNTRY varchar(100),
             PERSONAL_FAX varchar(50),
             PERSONAL_GENDER char(1),
             PERSONAL_ICQ varchar(50),
             PERSONAL_MAILBOX varchar(100),
             PERSONAL_MOBILE varchar(100),
             PERSONAL_NOTES	text,
             PERSONAL_PAGER	varchar(100),
             PERSONAL_PHONE	varchar(50),
             PERSONAL_PHOTO	int,
             PERSONAL_PROFESSION varchar(150),
             PERSONAL_STATE	varchar(100),
             PERSONAL_STREET text,
             PERSONAL_WWW varchar(1000),
             PERSONAL_ZIP varchar(20),
             STORED_HASH varchar(150),
             TIME_ZONE varchar(50),
             TIME_ZONE_OFFSET int,
             TITLE varchar(350),
             WORK_CITY varchar(100),
             WORK_COMPANY varchar(150),
             WORK_COUNTRY varchar(100),
             WORK_DEPARTMENT varchar(100),
             WORK_FAX varchar(100),
             WORK_LOGO int,
             WORK_MAILBOX varchar(100),
             WORK_NOTES	text,
             WORK_PAGER	varchar(100),
             WORK_PHONE	varchar(100),
             WORK_POSITION varchar(100),
             WORK_PROFILE text,
             WORK_STATE varchar(100),
             WORK_STREET text,
             WORK_WWW varchar(1000),
             WORK_ZIP varchar(20),
     primary key (id)        
); 
 
 ----------------------------------------------------
create table site_insert_order_new (
             id serial, 
             ORDER_ID int unique,
             USER_ID int REFERENCES site_user_new (ID),
             STATUS_ID varchar(10) REFERENCES site_sale_status_new (STATUS_ID),
             ACCOUNT_NUMBER	varchar(15),
             ADDITIONAL_INFO varchar(50),
             AFFILIATE_ID int,
             ALLOW_DELIVERY	char(1),
             BX_USER_ID	varchar(100),
             CANCELED char(1),
             "comments"	text,
             COMPANY_ID	int,
             CREATED_BY	int,
             CURRENCY char(3),
             DATE_ALLOW_DELIVERY timestamp,
             DATE_BILL timestamp,
             DATE_CANCELED timestamp,
             DATE_DEDUCTED timestamp,
             DATE_INSERT timestamp,
             DATE_LOCK timestamp,
             DATE_MARKED timestamp,
             DATE_PAY_BEFORE timestamp,
             DATE_PAYED timestamp,
             DATE_STATUS timestamp,
             DATE_UPDATE timestamp,
             DEDUCTED char(1),
             DELIVERY_DOC_DATE date,
             DELIVERY_DOC_NUM varchar(20),
             DELIVERY_ID varchar(20),
             DISCOUNT_VALUE	decimal,
             EMP_ALLOW_DELIVERY_ID int,
             EMP_CANCELED_ID int,
             EMP_DEDUCTED_ID int,
             EMP_MARKED_ID int,
             EMP_PAYED_ID int,
             EMP_STATUS_ID int,
             EXTERNAL_ORDER	char,
             ID_1C varchar,
             IS_RECURRING char,
             IS_SYNC_B24 char,
             LID varchar(5),
             LOCKED_BY int,
             MARKED	char(1),
             ORDER_TOPIC varchar(20),
             PAY_SYSTEM_ID int,
             PAY_VOUCHER_DATE date,
             PAY_VOUCHER_NUM varchar(20),
             PAYED char(1),
             PERSON_TYPE_ID	int,
             PRICE decimal,
             PRICE_DELIVERY	decimal,
             PRICE_PAYMENT decimal,
             PS_CURRENCY char,
             PS_RESPONSE_DATE timestamp,
             PS_STATUS varchar(10),
             PS_STATUS_CODE	varchar(10),
             PS_STATUS_DESCRIPTION varchar(50),
             PS_STATUS_MESSAGE varchar(100),
             PS_SUM	decimal,
             REASON_CANCELED varchar(255),
             REASON_MARKED varchar(255),
             REASON_UNDO_DEDUCTED varchar(255),
             RECOUNT_FLAG char(1),
             RECURRING_ID int,
             RESERVED char(1),
             RESPONSIBLE_ID	int,
             RUNNING char(1),
             SEARCH_CONTENT	text,
             STAT_GID varchar(255),
             STORE_ID int,
             SUM_PAID decimal,
             TAX_VALUE decimal,
             TRACKING_NUMBER varchar(15),
             UPDATED_1C	char(1),
             USER_DESCRIPTION varchar(1000),
             "version"	int,
             VERSION_1C	varchar(20),
             promocode	varchar(500),
     primary key (id)
  );
 
 
 
 -----------------------------------------
 create table site_update_order_new (
             id serial, 
             ORDER_ID int,
             USER_ID int REFERENCES site_user_new (ID),
             STATUS_ID varchar(10) REFERENCES site_sale_status_new (STATUS_ID),
             ACCOUNT_NUMBER	varchar(15),
             ADDITIONAL_INFO varchar(50),
             AFFILIATE_ID int,
             ALLOW_DELIVERY	char(1),
             BX_USER_ID	varchar(100),
             CANCELED char(1),
             "comments"	text,
             COMPANY_ID	int,
             CREATED_BY	int,
             CURRENCY char(3),
             DATE_ALLOW_DELIVERY timestamp,
             DATE_BILL timestamp,
             DATE_CANCELED timestamp,
             DATE_DEDUCTED timestamp,
             DATE_INSERT timestamp,
             DATE_LOCK timestamp,
             DATE_MARKED timestamp,
             DATE_PAY_BEFORE timestamp,
             DATE_PAYED timestamp,
             DATE_STATUS timestamp,
             DATE_UPDATE timestamp,
             DEDUCTED char(1),
             DELIVERY_DOC_DATE date,
             DELIVERY_DOC_NUM varchar(20),
             DELIVERY_ID varchar(20),
             DISCOUNT_VALUE	decimal,
             EMP_ALLOW_DELIVERY_ID int,
             EMP_CANCELED_ID int,
             EMP_DEDUCTED_ID int,
             EMP_MARKED_ID int,
             EMP_PAYED_ID int,
             EMP_STATUS_ID int,
             EXTERNAL_ORDER	char,
             ID_1C varchar,
             IS_RECURRING char,
             IS_SYNC_B24 char,
             LID varchar(5),
             LOCKED_BY int,
             MARKED	char(1),
             ORDER_TOPIC varchar(20),
             PAY_SYSTEM_ID int,
             PAY_VOUCHER_DATE date,
             PAY_VOUCHER_NUM varchar(20),
             PAYED char(1),
             PERSON_TYPE_ID	int,
             PRICE decimal,
             PRICE_DELIVERY	decimal,
             PRICE_PAYMENT decimal,
             PS_CURRENCY char,
             PS_RESPONSE_DATE timestamp,
             PS_STATUS char(1),
             PS_STATUS_CODE	varchar(10),
             PS_STATUS_DESCRIPTION varchar(50),
             PS_STATUS_MESSAGE varchar(100),
             PS_SUM	decimal,
             REASON_CANCELED varchar(255),
             REASON_MARKED varchar(255),
             REASON_UNDO_DEDUCTED varchar(255),
             RECOUNT_FLAG char(1),
             RECURRING_ID int,
             RESERVED char(1),
             RESPONSIBLE_ID	int,
             RUNNING char(1),
             SEARCH_CONTENT	text,
             STAT_GID varchar(255),
             STORE_ID int,
             SUM_PAID decimal,
             TAX_VALUE decimal,
             TRACKING_NUMBER varchar(15),
             UPDATED_1C	char(1),
             USER_DESCRIPTION varchar(1000),
             "version"	int,
             VERSION_1C	varchar(20),
             promocode	varchar(500),
     primary key (id)
  );
 
 ---------------------------------------------------
 create table site_insert_fuser_new (
             id serial,
             FUSER_ID int unique,
             DATE_INSERT timestamp,
             DATE_UPDATE timestamp,
             USER_ID int REFERENCES site_user_new (ID),
             CODE varchar(200),
     primary key (id)          
);

---------------------------------------------
create table site_update_fuser_new (
             id serial,
             FUSER_ID int,
             DATE_INSERT timestamp,
             DATE_UPDATE timestamp,
             USER_ID int REFERENCES site_user_new (ID),
             CODE varchar(200),
     primary key (id)          
); 
 
 -----------------------------------------------
 create table site_insert_basket_new(
             id serial,
             BASKET_ID	int unique,
             ORDER_ID int REFERENCES site_insert_order_new (ORDER_ID),
             FUSER_ID int REFERENCES site_insert_fuser_new (FUSER_ID),
             BARCODE_MULTI char(1),
             BASE_PRICE	decimal,
             CALLBACK_FUNC varchar(200),
             CAN_BUY char(1),
             CANCEL_CALLBACK_FUNC varchar(100),
             CURRENCY char(3),
             CUSTOM_PRICE char(1),
             DATE_INSERT timestamp,
             DATE_REFRESH timestamp,
             DATE_UPDATE timestamp,
             DEDUCTED char(1),
             DELAY char(1),
             DETAIL_PAGE_URL varchar(2000),
             DIMENSIONS	varchar(255),
             DISCOUNT_COUPON char(1),
             DISCOUNT_NAME varchar(200),
             DISCOUNT_PRICE	decimal,
             DISCOUNT_VALUE	varchar(50),
             LID varchar(5),
             MARKING_CODE_GROUP	varchar(300),
             MEASURE_CODE int,
             MEASURE_NAME varchar(10),
             "module" varchar(20),
             "name"	varchar(1000),
             NOTES	varchar(50),
             ORDER_CALLBACK_FUNC varchar(100),
             PAY_CALLBACK_FUNC varchar(100),
             PRICE decimal,
             PRICE_TYPE_ID int,
             PRODUCT_ID	int,
             PRODUCT_PRICE_ID int,
             PRODUCT_PROVIDER_CLASS varchar(100),
             QUANTITY double precision,
             RECOMMENDATION	varchar(1000),
             RESERVE_QUANTITY double precision,
             RESERVED char(1),
             SET_PARENT_ID int,
             SORT int,
             SUBSCRIBE char(1),
             "type" int,
             VAT_INCLUDED char(1),
             VAT_RATE decimal,
             WEIGHT double precision,
     primary key (id)
);

-----------------------------------------------------
 create table site_update_basket_new(
             id serial,
             BASKET_ID int,
             ORDER_ID int REFERENCES site_insert_order_new (ORDER_ID),
             FUSER_ID int REFERENCES site_insert_fuser_new (FUSER_ID),
             BARCODE_MULTI char(1),
             BASE_PRICE	decimal,
             CALLBACK_FUNC varchar(200),
             CAN_BUY char(1),
             CANCEL_CALLBACK_FUNC varchar(100),
             CURRENCY char(3),
             CUSTOM_PRICE char(1),
             DATE_INSERT timestamp,
             DATE_REFRESH timestamp,
             DATE_UPDATE timestamp,
             DEDUCTED char(1),
             DELAY char(1),
             DETAIL_PAGE_URL varchar(2000),
             DIMENSIONS	varchar(255),
             DISCOUNT_COUPON char(1),
             DISCOUNT_NAME varchar(200),
             DISCOUNT_PRICE	decimal,
             DISCOUNT_VALUE	varchar(50),
             LID varchar(5),
             MARKING_CODE_GROUP	varchar(300),
             MEASURE_CODE int,
             MEASURE_NAME varchar(10),
             "module" varchar(20),
             "name"	varchar(1000),
             NOTES	varchar(50),
             ORDER_CALLBACK_FUNC varchar(100),
             PAY_CALLBACK_FUNC varchar(100),
             PRICE decimal,
             PRICE_TYPE_ID int,
             PRODUCT_ID	int,
             PRODUCT_PRICE_ID int,
             PRODUCT_PROVIDER_CLASS varchar(100),
             QUANTITY double precision,
             RECOMMENDATION	varchar(1000),
             RESERVE_QUANTITY double precision,
             RESERVED char(1),
             SET_PARENT_ID int,
             SORT int,
             SUBSCRIBE char(1),
             "type" int,
             VAT_INCLUDED char(1),
             VAT_RATE decimal,
             WEIGHT double precision,
     primary key (id)
);

-------------------------------------------
create table site_guest_new (
             id serial,
             GUEST_ID int unique,
             TIMESTAMP_X timestamp,
             FAVORITES char(1),
             C_EVENTS int,
             SESSIONS int,
             HITS int,
             REPAIR char(1),
             FIRST_SESSION_ID int,
             FIRST_DATE timestamp,
             FIRST_URL_FROM text,
             FIRST_URL_TO text,
             FIRST_URL_TO_404 char,
             FIRST_SITE_ID varchar(10),
             FIRST_ADV_ID int,
             FIRST_REFERER1	varchar(2000),
             FIRST_REFERER2	varchar(2000),
             FIRST_REFERER3	varchar(2000),
             LAST_SESSION_ID int,
             LAST_DATE timestamp,
             LAST_USER_ID int,
             LAST_USER_AUTH	char(1),
             LAST_URL_LAST text,
             LAST_URL_LAST_404 char(1),
             LAST_USER_AGENT text,
             LAST_IP varchar(30),
             LAST_COOKIE text,
             LAST_LANGUAGE varchar(300),
             LAST_ADV_ID int,
             LAST_ADV_BACK char(1),
             LAST_REFERER1 varchar(2000),
             LAST_REFERER2 varchar(2000),
             LAST_REFERER3 varchar(2000),
             LAST_SITE_ID char(2),
             LAST_COUNTRY_ID char(2),
             LAST_CITY_ID int,
             LAST_CITY_INFO	text,
     primary key (id)
  );
 
 ----------------------------------------------
 create table site_session_new (
             id serial,
             SESSION_ID	int unique,
             GUEST_ID int REFERENCES site_guest_new (GUEST_ID),
             NEW_GUEST char(1),
             USER_ID int REFERENCES site_user_new (ID),
             USER_AUTH char(1),
             C_EVENTS int,
             HITS int,
             FAVORITES char(1),
             URL_FROM text,
             URL_TO	text,
             URL_TO_404	char(1),
             URL_LAST text,
             URL_LAST_404 char(1),
             USER_AGENT text,
             DATE_STAT date,
             DATE_FIRST timestamp,
             DATE_LAST timestamp,
             IP_FIRST varchar(30),
             IP_FIRST_NUMBER bigint,
             IP_LAST varchar(30),
             IP_LAST_NUMBER	bigint,
             FIRST_HIT_ID int,
             LAST_HIT_ID int,
             ADV_ID	int,
             ADV_BACK varchar(5),
             REFERER1 varchar(2000),
             REFERER2 varchar(2000),
             REFERER3 varchar(2000),
             STOP_LIST_ID int,
             COUNTRY_ID	char(2),
             CITY_ID int,
             FIRST_SITE_ID char(2),
             LAST_SITE_ID char(2),
     primary key (id)
  );
 
 

 --------------------------------------------------
 create table site_order_props_value_new (
             id serial,
             order_id int REFERENCES site_insert_order_new (ORDER_ID),
             date_insert timestamp,
             user_id int REFERENCES site_user_new (ID),
             city varchar(500),
             email varchar(500),
             company varchar(500),
             first_name varchar(500),
             last_name varchar(500),
             phone varchar(100),
             promocode varchar(500),
             customer_type_shop varchar(500),
             customer_type_org varchar(500),
             customer_type_company varchar(500),
             customer_type_personal varchar(500),
             entity_type varchar(255),
     primary key (id)
);
----------------------------------------------------

create table site_user_transact_new(
             id serial,
             transact_id int,
             timestamp_x timestamp,
	         transact_date timestamp,
             order_id int REFERENCES site_insert_order_new (ORDER_ID),
             user_id int REFERENCES site_user_new (ID),
             amount	decimal,
             currency char(3),
	         current_budget	decimal,
	         debit char(1),
	         description varchar(300),
	         employee_id int,
	         notes text,
	         payment_id int,
	 primary key (id)
);

-----------------------------------------------------
create table site_order_change_new(
             id serial,
             change_order_id int,
             order_id int REFERENCES site_insert_order_new (ORDER_ID),
             user_id int REFERENCES site_user_new (ID),
             "data" text,
	         date_create timestamp,
	         date_modify timestamp,
	         entity varchar(50),
	         entity_id int,
	         "type" varchar(100),
	 primary key (id)
);


--////////////////////////////////////////////////


-- Удалить таблицы
DROP table site_guest,
           site_insert_basket,
           site_insert_fuser,
           site_insert_order,
           site_location,
           site_location_city,
           site_location_country,
           site_order_props_value,
           site_order_props_value_2,
           site_person_type,
           site_session,
           site_update_basket,
           site_update_fuser,
           site_update_order,
           site_user,
           site_user_activity
           cascade;

-- Показать наименование таблиц в базе
with a as (
SELECT table_name, column_name 
  FROM information_schema.columns
 WHERE table_catalog = 'test_char' and table_schema = 'public' order by table_name
 )
 select distinct table_name from a
 
 -- или
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'tablename'
ORDER BY ordinal_position;
 
 
 -- Очистить таблицы
TRUNCATE site_location_country_new RESTART IDENTITY
 



